[supervisord]
nodaemon=true
logfile=/tmp/supervisord.log
pidfile=/tmp/supervisord.pid

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/tmp/nginx.log
stderr_logfile=/tmp/nginx-error.log

[program:php-fpm]
command=php-fpm -F
autostart=true
autorestart=true
stdout_logfile=/tmp/php-fpm.log
stderr_logfile=/tmp/php-fpm-error.log

[program:migrate]
command=php /app/artisan migrate --force
autostart=true
autorestart=false
stdout_logfile=/tmp/migrate.log
stderr_logfile=/tmp/migrate-error.log
startsecs=0
